import AppKit
import Foundation

struct MetadataField: Identifiable, Sendable {
    let id: String
    let label: String
    let value: String

    init(id: String? = nil, label: String, value: String) {
        self.id = id ?? label
        self.label = label
        self.value = String(value.prefix(2_000))
    }
}

struct MetadataSection: Identifiable, Sendable {
    let id: String
    let title: String
    let fields: [MetadataField]

    init(id: String? = nil, title: String, fields: [MetadataField]) {
        self.id = id ?? title
        self.title = title
        self.fields = fields
    }
}

/// Metadata stays local. Images are generated by Quick Look and attached on the main actor.
struct FileMetadata: @unchecked Sendable {
    let url: URL
    let title: String
    let kind: String
    var sections: [MetadataSection]
    var textPreview: String?
    var thumbnail: NSImage?

    init(url: URL, title: String, kind: String, sections: [MetadataSection],
         textPreview: String? = nil, thumbnail: NSImage? = nil) {
        self.url = url
        self.title = title
        self.kind = kind
        self.sections = sections
        self.textPreview = textPreview
        self.thumbnail = thumbnail
    }
}
