import AppKit
import Foundation

struct MetadataField: Identifiable, Sendable {
    let id: String
    let label: String
    let value: String

    init(id: String? = nil, label: String, value: String) {
        self.id = id ?? label
        self.label = label
        self.value = String(value.prefix(2_000))
    }
}

struct MetadataSection: Identifiable, Sendable {
    let id: String
    let title: String
    let fields: [MetadataField]

    init(id: String? = nil, title: String, fields: [MetadataField]) {
        self.id = id ?? title
        self.title = title
        // Native metadata can repeat a label for different tracks/locales.
        // Preserve every value while giving SwiftUI a unique, deterministic identity.
        var identities = Set<String>()
        self.fields = fields.map { field in
            var candidate = field.id
            var suffix = 1
            while identities.contains(candidate) {
                candidate = "\(field.id)#\(suffix)"
                suffix += 1
            }
            identities.insert(candidate)
            return candidate == field.id ? field : MetadataField(id: candidate, label: field.label, value: field.value)
        }
    }
}

/// Metadata stays local. Images are generated by Quick Look and attached on the main actor.
struct FileMetadata: @unchecked Sendable {
    let url: URL
    let title: String
    let kind: String
    var sections: [MetadataSection]
    var textPreview: String?
    var thumbnail: NSImage?

    init(url: URL, title: String, kind: String, sections: [MetadataSection],
         textPreview: String? = nil, thumbnail: NSImage? = nil) {
        self.url = url
        self.title = title
        self.kind = kind
        self.sections = sections
        self.textPreview = textPreview
        self.thumbnail = thumbnail
    }
}
